name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then echo "Error: HF_TOKEN is empty!" && exit 1; fi
          git push https://annepagaanvesh:$HF_TOKEN@huggingface.co/spaces/annepagaanvesh/clause-ai-agent main --force
