name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then echo "Error: HF_TOKEN is empty!" && exit 1; fi
          # Remove the git history so we don't send old deleted binary files (like .zip and .jpg)
          rm -rf .git
          git init
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy to Hugging Face"
          git push https://annepagaanvesh:$HF_TOKEN@huggingface.co/spaces/annepagaanvesh/clause-ai-agent HEAD:main --force
